//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public int Person_Id { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
